package goclickzetta

import (
	"bytes"
	"context"
	"errors"
	"io"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/valyala/fastjson"
)

// recordingMockClient records the path and payload of every Post so tests can
// assert on the request actually sent to the server.
type recordingMockClient struct {
	mu       sync.Mutex
	requests []recordedRequest
	body     []byte
	onPost   func()
	// errFor 按请求路径决定该次 Post 是否失败
	errFor func(path string) error
}

type recordedRequest struct {
	path string
	body []byte
}

func (m *recordingMockClient) Post(_ context.Context, u *url.URL, _ map[string]string, body []byte, _ time.Duration) (*http.Response, error) {
	m.mu.Lock()
	m.requests = append(m.requests, recordedRequest{path: u.Path, body: append([]byte(nil), body...)})
	m.mu.Unlock()
	if m.onPost != nil {
		m.onPost()
	}
	if m.errFor != nil {
		if err := m.errFor(u.Path); err != nil {
			return nil, err
		}
	}
	respBody := m.body
	if respBody == nil {
		respBody = []byte(`{"status":{"state":"SUCCEED"}}`)
	}
	return &http.Response{
		StatusCode: 200,
		Body:       io.NopCloser(bytes.NewReader(respBody)),
	}, nil
}

func (m *recordingMockClient) Get(_ context.Context, _ *url.URL, _ map[string]string, _ time.Duration) (*http.Response, error) {
	return nil, errors.New("not implemented")
}

func (m *recordingMockClient) Close() error { return nil }

func (m *recordingMockClient) requestsTo(suffix string) []recordedRequest {
	m.mu.Lock()
	defer m.mu.Unlock()
	var out []recordedRequest
	for _, req := range m.requests {
		if strings.HasSuffix(req.path, suffix) {
			out = append(out, req)
		}
	}
	return out
}

func (m *recordingMockClient) requestCount() int {
	m.mu.Lock()
	defer m.mu.Unlock()
	return len(m.requests)
}

func parseRequest(t *testing.T, body []byte) *fastjson.Value {
	t.Helper()
	val, err := fastjson.ParseBytes(body)
	if err != nil {
		t.Fatalf("request body is not valid json: %v", err)
	}
	return val
}

// onlyCancelRequest asserts exactly one cancel was sent and returns its payload.
func onlyCancelRequest(t *testing.T, mock *recordingMockClient) *fastjson.Value {
	t.Helper()
	reqs := mock.requestsTo("cancelJob")
	if len(reqs) != 1 {
		t.Fatalf("expected 1 cancelJob request, got %d", len(reqs))
	}
	return parseRequest(t, reqs[0].body)
}

// A job cancelled by the SDK's own timeout watchdog must be attributable to the
// timeout, not to the caller.
func TestCheckJobTimeout_CancelsWithTimeoutUserAgent(t *testing.T) {
	mock := &recordingMockClient{}
	conn := newTestConn(mock)

	timedOut := conn.checkJobTimeout(1, time.Now().Add(-2*time.Second), jobId{ID: "job-timeout"}, map[string]string{})
	if !timedOut {
		t.Fatal("expected the job to be reported as timed out")
	}

	req := onlyCancelRequest(t, mock)
	if got := string(req.GetStringBytes("user_agent")); got != "gosdk_by_timeout" {
		t.Errorf("user_agent = %q, want %q", got, "gosdk_by_timeout")
	}
	if got := string(req.GetStringBytes("job_id", "id")); got != "job-timeout" {
		t.Errorf("job_id.id = %q, want %q", got, "job-timeout")
	}
}

func TestCancelJob_DefaultsToUserUserAgent(t *testing.T) {
	mock := &recordingMockClient{}
	conn := newTestConnWithRetries(mock, 1)

	if err := conn.CancelJob("job-1", ""); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	req := onlyCancelRequest(t, mock)
	if got := string(req.GetStringBytes("user_agent")); got != "gosdk_by_user" {
		t.Errorf("user_agent = %q, want %q", got, "gosdk_by_user")
	}
	if got := string(req.GetStringBytes("job_id", "id")); got != "job-1" {
		t.Errorf("job_id.id = %q, want %q", got, "job-1")
	}
	if got := string(req.GetStringBytes("job_id", "workspace")); got != "ws" {
		t.Errorf("job_id.workspace = %q, want %q", got, "ws")
	}
}

func TestCancelJob_KeepsCallerUserAgent(t *testing.T) {
	mock := &recordingMockClient{}
	conn := newTestConnWithRetries(mock, 1)

	if err := conn.CancelJob("job-1", "my-app"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	req := onlyCancelRequest(t, mock)
	if got := string(req.GetStringBytes("user_agent")); got != "my-app" {
		t.Errorf("user_agent = %q, want %q", got, "my-app")
	}
}

// Cancel targets whatever job the connection is running, so it must pick up the
// job id generated by execInternal rather than require the caller to know it.
func TestCancel_CancelsJobRunningOnConnection(t *testing.T) {
	mock := &recordingMockClient{}
	conn := newTestConnWithRetries(mock, 1)

	var cancelErr error
	cancelSent := false
	mock.onPost = func() {
		if cancelSent {
			return
		}
		cancelSent = true
		cancelErr = conn.Cancel("")
	}

	if _, err := conn.execInternal(context.Background(), "select 1\n;", nil); err != nil {
		t.Fatalf("unexpected exec error: %v", err)
	}
	if cancelErr != nil {
		t.Fatalf("Cancel during exec failed: %v", cancelErr)
	}

	submitted := mock.requestsTo("submitJob")
	if len(submitted) != 1 {
		t.Fatalf("expected 1 submitJob request, got %d", len(submitted))
	}
	runningJobID := string(parseRequest(t, submitted[0].body).GetStringBytes("jobDesc", "jobId", "id"))
	if runningJobID == "" {
		t.Fatal("could not read the job id out of the submitJob request")
	}

	req := onlyCancelRequest(t, mock)
	if got := string(req.GetStringBytes("job_id", "id")); got != runningJobID {
		t.Errorf("cancelled job_id.id = %q, want the running job %q", got, runningJobID)
	}
	if got := string(req.GetStringBytes("user_agent")); got != "gosdk_by_user" {
		t.Errorf("user_agent = %q, want %q", got, "gosdk_by_user")
	}
}

func TestCancel_WithoutRunningJobReportsError(t *testing.T) {
	mock := &recordingMockClient{}
	conn := newTestConn(mock)

	if err := conn.Cancel(""); err == nil {
		t.Fatal("expected an error when no job is running on the connection")
	}
	if n := mock.requestCount(); n != 0 {
		t.Errorf("expected no request to be sent, got %d", n)
	}
}

// Once a query finishes, the connection no longer has a job to cancel.
func TestCancel_AfterQueryCompletesReportsError(t *testing.T) {
	mock := &recordingMockClient{}
	conn := newTestConnWithRetries(mock, 1)

	if _, err := conn.execInternal(context.Background(), "select 1\n;", nil); err != nil {
		t.Fatalf("unexpected exec error: %v", err)
	}

	if err := conn.Cancel(""); err == nil {
		t.Fatal("expected an error once the query has completed")
	}
	if reqs := mock.requestsTo("cancelJob"); len(reqs) != 0 {
		t.Errorf("expected no cancelJob request, got %d", len(reqs))
	}
}

// failingSubmitMock 让提交一直失败，从而进入提交重试逻辑
func failingSubmitMock() *recordingMockClient {
	return &recordingMockClient{
		errFor: func(path string) error {
			if strings.HasSuffix(path, "submitJob") {
				return errors.New("submit unavailable")
			}
			return nil
		},
	}
}

// 取消之后继续重试提交，等于把一个已经取消的作业重新交上去。
func TestCancel_StopsSubmitRetries(t *testing.T) {
	mock := failingSubmitMock()
	conn := newTestConnWithRetries(mock, 3)

	cancelSent := false
	mock.onPost = func() {
		if cancelSent {
			return
		}
		cancelSent = true
		if err := conn.Cancel(""); err != nil {
			t.Errorf("Cancel during submit failed: %v", err)
		}
	}

	_, err := conn.execInternal(context.Background(), "select 1\n;", nil)
	if err == nil {
		t.Fatal("expected execInternal to report an error")
	}
	// 失败原因要指向取消，否则调用方分不清是取消还是重试耗尽
	if !strings.Contains(err.Error(), "cancel") {
		t.Errorf("error = %q, want it to report the cancellation", err)
	}

	if n := len(mock.requestsTo("submitJob")); n != 1 {
		t.Errorf("submitJob attempts = %d, want 1 (cancelled after the first attempt)", n)
	}
}

// 取消别的 job 不该影响本连接上正在提交的 job。
func TestCancelJob_OtherJobDoesNotStopSubmitRetries(t *testing.T) {
	mock := failingSubmitMock()
	conn := newTestConnWithRetries(mock, 2)

	cancelSent := false
	mock.onPost = func() {
		if cancelSent {
			return
		}
		cancelSent = true
		if err := conn.CancelJob("some-other-job", ""); err != nil {
			t.Errorf("CancelJob failed: %v", err)
		}
	}

	if _, err := conn.execInternal(context.Background(), "select 1\n;", nil); err == nil {
		t.Fatal("expected execInternal to report an error")
	}

	if n := len(mock.requestsTo("submitJob")); n != 2 {
		t.Errorf("submitJob attempts = %d, want 2 (unrelated cancel must not stop retries)", n)
	}
}

// 取消状态属于单次查询，下一条查询必须能重新提交。
func TestCancel_DoesNotBlockLaterQueries(t *testing.T) {
	mock := failingSubmitMock()
	conn := newTestConnWithRetries(mock, 1)

	cancelSent := false
	mock.onPost = func() {
		if cancelSent {
			return
		}
		cancelSent = true
		if err := conn.Cancel(""); err != nil {
			t.Errorf("Cancel during submit failed: %v", err)
		}
	}

	if _, err := conn.execInternal(context.Background(), "select 1\n;", nil); err == nil {
		t.Fatal("expected the first query to report an error")
	}
	if _, err := conn.execInternal(context.Background(), "select 2\n;", nil); err == nil {
		t.Fatal("expected the second query to report an error")
	}

	if n := len(mock.requestsTo("submitJob")); n != 2 {
		t.Errorf("submitJob attempts = %d, want 2 (the second query must still be submitted)", n)
	}
}

// 取消请求自己失败时不能当成已取消，否则会白白丢掉一次本可成功的提交。
func TestCancel_FailedRequestDoesNotStopSubmitRetries(t *testing.T) {
	mock := &recordingMockClient{
		errFor: func(path string) error {
			if strings.HasSuffix(path, "submitJob") {
				return errors.New("submit unavailable")
			}
			if strings.HasSuffix(path, "cancelJob") {
				return errors.New("cancel unavailable")
			}
			return nil
		},
	}
	conn := newTestConnWithRetries(mock, 2)

	cancelTried := false
	var cancelErr error
	mock.onPost = func() {
		if cancelTried {
			return
		}
		cancelTried = true
		cancelErr = conn.Cancel("")
	}

	if _, err := conn.execInternal(context.Background(), "select 1\n;", nil); err == nil {
		t.Fatal("expected execInternal to report an error")
	}
	if cancelErr == nil {
		t.Fatal("expected Cancel to surface the failed cancel request")
	}
	if n := len(mock.requestsTo("submitJob")); n != 2 {
		t.Errorf("submitJob attempts = %d, want 2 (a failed cancel must not stop retries)", n)
	}
}

// 只有空白字符的 user agent 等同于没传。
func TestCancelJob_BlankUserAgentFallsBackToDefault(t *testing.T) {
	mock := &recordingMockClient{}
	conn := newTestConnWithRetries(mock, 1)

	if err := conn.CancelJob("job-1", "   "); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	req := onlyCancelRequest(t, mock)
	if got := string(req.GetStringBytes("user_agent")); got != "gosdk_by_user" {
		t.Errorf("user_agent = %q, want %q", got, "gosdk_by_user")
	}
}
