// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: util/file_format_type.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileFormatType int32

const (
	FileFormatType_TEXT        FileFormatType = 0
	FileFormatType_PARQUET     FileFormatType = 1
	FileFormatType_ORC         FileFormatType = 2
	FileFormatType_AVRO        FileFormatType = 3
	FileFormatType_CSV         FileFormatType = 4
	FileFormatType_ARROW       FileFormatType = 5 // Arrow IPC format
	FileFormatType_HIVE_RESULT FileFormatType = 96
	FileFormatType_DUMMY       FileFormatType = 97
	FileFormatType_MEMORY      FileFormatType = 98
	FileFormatType_ICEBERG     FileFormatType = 99 //TODO(king) HACK, remove this after iceberg jni API removed
)

// Enum value maps for FileFormatType.
var (
	FileFormatType_name = map[int32]string{
		0:  "TEXT",
		1:  "PARQUET",
		2:  "ORC",
		3:  "AVRO",
		4:  "CSV",
		5:  "ARROW",
		96: "HIVE_RESULT",
		97: "DUMMY",
		98: "MEMORY",
		99: "ICEBERG",
	}
	FileFormatType_value = map[string]int32{
		"TEXT":        0,
		"PARQUET":     1,
		"ORC":         2,
		"AVRO":        3,
		"CSV":         4,
		"ARROW":       5,
		"HIVE_RESULT": 96,
		"DUMMY":       97,
		"MEMORY":      98,
		"ICEBERG":     99,
	}
)

func (x FileFormatType) Enum() *FileFormatType {
	p := new(FileFormatType)
	*p = x
	return p
}

func (x FileFormatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileFormatType) Descriptor() protoreflect.EnumDescriptor {
	return file_util_file_format_type_proto_enumTypes[0].Descriptor()
}

func (FileFormatType) Type() protoreflect.EnumType {
	return &file_util_file_format_type_proto_enumTypes[0]
}

func (x FileFormatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileFormatType.Descriptor instead.
func (FileFormatType) EnumDescriptor() ([]byte, []int) {
	return file_util_file_format_type_proto_rawDescGZIP(), []int{0}
}

var File_util_file_format_type_proto protoreflect.FileDescriptor

var file_util_file_format_type_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75,
	0x74, 0x69, 0x6c, 0x2a, 0x83, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x50, 0x41, 0x52, 0x51, 0x55, 0x45, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x4f, 0x52, 0x43, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x56, 0x52, 0x4f, 0x10, 0x03,
	0x12, 0x07, 0x0a, 0x03, 0x43, 0x53, 0x56, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x52, 0x52,
	0x4f, 0x57, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x49, 0x56, 0x45, 0x5f, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x10, 0x60, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x55, 0x4d, 0x4d, 0x59, 0x10, 0x61,
	0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x4d, 0x4f, 0x52, 0x59, 0x10, 0x62, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x43, 0x45, 0x42, 0x45, 0x52, 0x47, 0x10, 0x63, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74,
	0x74, 0x61, 0x2f, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x75, 0x6c, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2f,
	0x75, 0x74, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_util_file_format_type_proto_rawDescOnce sync.Once
	file_util_file_format_type_proto_rawDescData = file_util_file_format_type_proto_rawDesc
)

func file_util_file_format_type_proto_rawDescGZIP() []byte {
	file_util_file_format_type_proto_rawDescOnce.Do(func() {
		file_util_file_format_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_util_file_format_type_proto_rawDescData)
	})
	return file_util_file_format_type_proto_rawDescData
}

var file_util_file_format_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_util_file_format_type_proto_goTypes = []interface{}{
	(FileFormatType)(0), // 0: util.FileFormatType
}
var file_util_file_format_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_util_file_format_type_proto_init() }
func file_util_file_format_type_proto_init() {
	if File_util_file_format_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_util_file_format_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_file_format_type_proto_goTypes,
		DependencyIndexes: file_util_file_format_type_proto_depIdxs,
		EnumInfos:         file_util_file_format_type_proto_enumTypes,
	}.Build()
	File_util_file_format_type_proto = out.File
	file_util_file_format_type_proto_rawDesc = nil
	file_util_file_format_type_proto_goTypes = nil
	file_util_file_format_type_proto_depIdxs = nil
}
