// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: util/file_system.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileSystemType int32

const (
	FileSystemType_LOCAL FileSystemType = 0
	FileSystemType_OSS   FileSystemType = 1
	FileSystemType_CACHE FileSystemType = 2
	FileSystemType_RPC   FileSystemType = 3
	FileSystemType_COS   FileSystemType = 4
)

// Enum value maps for FileSystemType.
var (
	FileSystemType_name = map[int32]string{
		0: "LOCAL",
		1: "OSS",
		2: "CACHE",
		3: "RPC",
		4: "COS",
	}
	FileSystemType_value = map[string]int32{
		"LOCAL": 0,
		"OSS":   1,
		"CACHE": 2,
		"RPC":   3,
		"COS":   4,
	}
)

func (x FileSystemType) Enum() *FileSystemType {
	p := new(FileSystemType)
	*p = x
	return p
}

func (x FileSystemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileSystemType) Descriptor() protoreflect.EnumDescriptor {
	return file_util_file_system_proto_enumTypes[0].Descriptor()
}

func (FileSystemType) Type() protoreflect.EnumType {
	return &file_util_file_system_proto_enumTypes[0]
}

func (x FileSystemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileSystemType.Descriptor instead.
func (FileSystemType) EnumDescriptor() ([]byte, []int) {
	return file_util_file_system_proto_rawDescGZIP(), []int{0}
}

var File_util_file_system_proto protoreflect.FileDescriptor

var file_util_file_system_proto_rawDesc = []byte{
	0x0a, 0x16, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x74, 0x69, 0x6c, 0x2a, 0x41,
	0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4f,
	0x53, 0x53, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x41, 0x43, 0x48, 0x45, 0x10, 0x02, 0x12,
	0x07, 0x0a, 0x03, 0x52, 0x50, 0x43, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x4f, 0x53, 0x10,
	0x04, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x63, 0x6c, 0x69,
	0x63, 0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62,
	0x75, 0x6c, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_util_file_system_proto_rawDescOnce sync.Once
	file_util_file_system_proto_rawDescData = file_util_file_system_proto_rawDesc
)

func file_util_file_system_proto_rawDescGZIP() []byte {
	file_util_file_system_proto_rawDescOnce.Do(func() {
		file_util_file_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_util_file_system_proto_rawDescData)
	})
	return file_util_file_system_proto_rawDescData
}

var file_util_file_system_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_util_file_system_proto_goTypes = []interface{}{
	(FileSystemType)(0), // 0: util.FileSystemType
}
var file_util_file_system_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_util_file_system_proto_init() }
func file_util_file_system_proto_init() {
	if File_util_file_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_util_file_system_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_file_system_proto_goTypes,
		DependencyIndexes: file_util_file_system_proto_depIdxs,
		EnumInfos:         file_util_file_system_proto_enumTypes,
	}.Build()
	File_util_file_system_proto = out.File
	file_util_file_system_proto_rawDesc = nil
	file_util_file_system_proto_goTypes = nil
	file_util_file_system_proto_depIdxs = nil
}
