// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: util/function_meta.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Uri  string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *FunctionResource) Reset() {
	*x = FunctionResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_function_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionResource) ProtoMessage() {}

func (x *FunctionResource) ProtoReflect() protoreflect.Message {
	mi := &file_util_function_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionResource.ProtoReflect.Descriptor instead.
func (*FunctionResource) Descriptor() ([]byte, []int) {
	return file_util_function_meta_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FunctionResource) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type FunctionResourceList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources []*FunctionResource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *FunctionResourceList) Reset() {
	*x = FunctionResourceList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_function_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionResourceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionResourceList) ProtoMessage() {}

func (x *FunctionResourceList) ProtoReflect() protoreflect.Message {
	mi := &file_util_function_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionResourceList.ProtoReflect.Descriptor instead.
func (*FunctionResourceList) Descriptor() ([]byte, []int) {
	return file_util_function_meta_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionResourceList) GetResources() []*FunctionResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type RemoteEntrypoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InternalUrl string                       `protobuf:"bytes,1,opt,name=internal_url,json=internalUrl,proto3" json:"internal_url,omitempty"`
	ExternalUrl string                       `protobuf:"bytes,2,opt,name=external_url,json=externalUrl,proto3" json:"external_url,omitempty"`
	Protocol    string                       `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	VendorType  string                       `protobuf:"bytes,4,opt,name=vendor_type,json=vendorType,proto3" json:"vendor_type,omitempty"`
	VendorInfo  *RemoteEntrypoint_VendorInfo `protobuf:"bytes,5,opt,name=vendor_info,json=vendorInfo,proto3" json:"vendor_info,omitempty"`
}

func (x *RemoteEntrypoint) Reset() {
	*x = RemoteEntrypoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_function_meta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteEntrypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteEntrypoint) ProtoMessage() {}

func (x *RemoteEntrypoint) ProtoReflect() protoreflect.Message {
	mi := &file_util_function_meta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteEntrypoint.ProtoReflect.Descriptor instead.
func (*RemoteEntrypoint) Descriptor() ([]byte, []int) {
	return file_util_function_meta_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteEntrypoint) GetInternalUrl() string {
	if x != nil {
		return x.InternalUrl
	}
	return ""
}

func (x *RemoteEntrypoint) GetExternalUrl() string {
	if x != nil {
		return x.ExternalUrl
	}
	return ""
}

func (x *RemoteEntrypoint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RemoteEntrypoint) GetVendorType() string {
	if x != nil {
		return x.VendorType
	}
	return ""
}

func (x *RemoteEntrypoint) GetVendorInfo() *RemoteEntrypoint_VendorInfo {
	if x != nil {
		return x.VendorInfo
	}
	return nil
}

type Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category         string                `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	ExecType         string                `protobuf:"bytes,2,opt,name=exec_type,json=execType,proto3" json:"exec_type,omitempty"`
	Signature        string                `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Handler          string                `protobuf:"bytes,4,opt,name=handler,proto3" json:"handler,omitempty"`
	ConnectionId     int64                 `protobuf:"varint,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Resources        *FunctionResourceList `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	RemoteEntrypoint *RemoteEntrypoint     `protobuf:"bytes,7,opt,name=remote_entrypoint,json=remoteEntrypoint,proto3" json:"remote_entrypoint,omitempty"`
}

func (x *Function) Reset() {
	*x = Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_function_meta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_util_function_meta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_util_function_meta_proto_rawDescGZIP(), []int{3}
}

func (x *Function) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Function) GetExecType() string {
	if x != nil {
		return x.ExecType
	}
	return ""
}

func (x *Function) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Function) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *Function) GetConnectionId() int64 {
	if x != nil {
		return x.ConnectionId
	}
	return 0
}

func (x *Function) GetResources() *FunctionResourceList {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Function) GetRemoteEntrypoint() *RemoteEntrypoint {
	if x != nil {
		return x.RemoteEntrypoint
	}
	return nil
}

type RemoteEntrypoint_VendorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service  string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Function string `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *RemoteEntrypoint_VendorInfo) Reset() {
	*x = RemoteEntrypoint_VendorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_function_meta_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteEntrypoint_VendorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteEntrypoint_VendorInfo) ProtoMessage() {}

func (x *RemoteEntrypoint_VendorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_util_function_meta_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteEntrypoint_VendorInfo.ProtoReflect.Descriptor instead.
func (*RemoteEntrypoint_VendorInfo) Descriptor() ([]byte, []int) {
	return file_util_function_meta_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RemoteEntrypoint_VendorInfo) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RemoteEntrypoint_VendorInfo) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

var File_util_function_meta_proto protoreflect.FileDescriptor

var file_util_function_meta_proto_rawDesc = []byte{
	0x0a, 0x18, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x74, 0x69, 0x6c,
	0x22, 0x38, 0x0a, 0x10, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0x4c, 0x0a, 0x14, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x9d, 0x02, 0x0a, 0x10, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c,
	0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12,
	0x1f, 0x0a, 0x0b, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x42, 0x0a, 0x0b, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x56, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x42, 0x0a, 0x0a, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9f, 0x02, 0x0a, 0x08, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x65, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x11, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x10, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65,
	0x74, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x75, 0x6c, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x2f, 0x75, 0x74, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_util_function_meta_proto_rawDescOnce sync.Once
	file_util_function_meta_proto_rawDescData = file_util_function_meta_proto_rawDesc
)

func file_util_function_meta_proto_rawDescGZIP() []byte {
	file_util_function_meta_proto_rawDescOnce.Do(func() {
		file_util_function_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_util_function_meta_proto_rawDescData)
	})
	return file_util_function_meta_proto_rawDescData
}

var file_util_function_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_util_function_meta_proto_goTypes = []interface{}{
	(*FunctionResource)(nil),            // 0: util.FunctionResource
	(*FunctionResourceList)(nil),        // 1: util.FunctionResourceList
	(*RemoteEntrypoint)(nil),            // 2: util.RemoteEntrypoint
	(*Function)(nil),                    // 3: util.Function
	(*RemoteEntrypoint_VendorInfo)(nil), // 4: util.RemoteEntrypoint.VendorInfo
}
var file_util_function_meta_proto_depIdxs = []int32{
	0, // 0: util.FunctionResourceList.resources:type_name -> util.FunctionResource
	4, // 1: util.RemoteEntrypoint.vendor_info:type_name -> util.RemoteEntrypoint.VendorInfo
	1, // 2: util.Function.resources:type_name -> util.FunctionResourceList
	2, // 3: util.Function.remote_entrypoint:type_name -> util.RemoteEntrypoint
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_util_function_meta_proto_init() }
func file_util_function_meta_proto_init() {
	if File_util_function_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_util_function_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_util_function_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionResourceList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_util_function_meta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteEntrypoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_util_function_meta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_util_function_meta_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteEntrypoint_VendorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_util_function_meta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_function_meta_proto_goTypes,
		DependencyIndexes: file_util_function_meta_proto_depIdxs,
		MessageInfos:      file_util_function_meta_proto_msgTypes,
	}.Build()
	File_util_function_meta_proto = out.File
	file_util_function_meta_proto_rawDesc = nil
	file_util_function_meta_proto_goTypes = nil
	file_util_function_meta_proto_depIdxs = nil
}
