// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: util/network_policy.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content *NetworkPolicyData `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *NetworkPolicy) Reset() {
	*x = NetworkPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_network_policy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicy) ProtoMessage() {}

func (x *NetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_util_network_policy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicy.ProtoReflect.Descriptor instead.
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return file_util_network_policy_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkPolicy) GetContent() *NetworkPolicyData {
	if x != nil {
		return x.Content
	}
	return nil
}

type NetworkPolicyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkspaceList []string `protobuf:"bytes,1,rep,name=workspaceList,proto3" json:"workspaceList,omitempty"`
	UsernameList  []string `protobuf:"bytes,2,rep,name=usernameList,proto3" json:"usernameList,omitempty"`
	BlockedList   []string `protobuf:"bytes,3,rep,name=blockedList,proto3" json:"blockedList,omitempty"`
	AllowedList   []string `protobuf:"bytes,4,rep,name=allowedList,proto3" json:"allowedList,omitempty"`
}

func (x *NetworkPolicyData) Reset() {
	*x = NetworkPolicyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_network_policy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkPolicyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyData) ProtoMessage() {}

func (x *NetworkPolicyData) ProtoReflect() protoreflect.Message {
	mi := &file_util_network_policy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyData.ProtoReflect.Descriptor instead.
func (*NetworkPolicyData) Descriptor() ([]byte, []int) {
	return file_util_network_policy_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkPolicyData) GetWorkspaceList() []string {
	if x != nil {
		return x.WorkspaceList
	}
	return nil
}

func (x *NetworkPolicyData) GetUsernameList() []string {
	if x != nil {
		return x.UsernameList
	}
	return nil
}

func (x *NetworkPolicyData) GetBlockedList() []string {
	if x != nil {
		return x.BlockedList
	}
	return nil
}

func (x *NetworkPolicyData) GetAllowedList() []string {
	if x != nil {
		return x.AllowedList
	}
	return nil
}

var File_util_network_policy_proto protoreflect.FileDescriptor

var file_util_network_policy_proto_rawDesc = []byte{
	0x0a, 0x19, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x74, 0x69,
	0x6c, 0x22, 0x42, 0x0a, 0x0d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xa1, 0x01, 0x0a, 0x11, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74,
	0x74, 0x61, 0x2f, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x75, 0x6c, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2f,
	0x75, 0x74, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_util_network_policy_proto_rawDescOnce sync.Once
	file_util_network_policy_proto_rawDescData = file_util_network_policy_proto_rawDesc
)

func file_util_network_policy_proto_rawDescGZIP() []byte {
	file_util_network_policy_proto_rawDescOnce.Do(func() {
		file_util_network_policy_proto_rawDescData = protoimpl.X.CompressGZIP(file_util_network_policy_proto_rawDescData)
	})
	return file_util_network_policy_proto_rawDescData
}

var file_util_network_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_util_network_policy_proto_goTypes = []interface{}{
	(*NetworkPolicy)(nil),     // 0: util.NetworkPolicy
	(*NetworkPolicyData)(nil), // 1: util.NetworkPolicyData
}
var file_util_network_policy_proto_depIdxs = []int32{
	1, // 0: util.NetworkPolicy.content:type_name -> util.NetworkPolicyData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_util_network_policy_proto_init() }
func file_util_network_policy_proto_init() {
	if File_util_network_policy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_util_network_policy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_util_network_policy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkPolicyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_util_network_policy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_network_policy_proto_goTypes,
		DependencyIndexes: file_util_network_policy_proto_depIdxs,
		MessageInfos:      file_util_network_policy_proto_msgTypes,
	}.Build()
	File_util_network_policy_proto = out.File
	file_util_network_policy_proto_rawDesc = nil
	file_util_network_policy_proto_goTypes = nil
	file_util_network_policy_proto_depIdxs = nil
}
