// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: util/object_identifier.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectType int32

const (
	ObjectType_UNKNOWN         ObjectType = 0
	ObjectType_INSTANCE        ObjectType = 1
	ObjectType_NETWORK_POLICY  ObjectType = 2
	ObjectType_WORKSPACE       ObjectType = 100
	ObjectType_SHARE           ObjectType = 101
	ObjectType_SCHEMA          ObjectType = 200
	ObjectType_DATALAKE        ObjectType = 201
	ObjectType_USER            ObjectType = 202
	ObjectType_ROLE            ObjectType = 203
	ObjectType_VIRTUAL_CLUSTER ObjectType = 104
	ObjectType_JOB             ObjectType = 205
	ObjectType_CONNECTION      ObjectType = 206
	ObjectType_TABLE           ObjectType = 300
	ObjectType_FUNCTION        ObjectType = 301
	ObjectType_INDEX           ObjectType = 400
	ObjectType_FILE            ObjectType = 500
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0:   "UNKNOWN",
		1:   "INSTANCE",
		2:   "NETWORK_POLICY",
		100: "WORKSPACE",
		101: "SHARE",
		200: "SCHEMA",
		201: "DATALAKE",
		202: "USER",
		203: "ROLE",
		104: "VIRTUAL_CLUSTER",
		205: "JOB",
		206: "CONNECTION",
		300: "TABLE",
		301: "FUNCTION",
		400: "INDEX",
		500: "FILE",
	}
	ObjectType_value = map[string]int32{
		"UNKNOWN":         0,
		"INSTANCE":        1,
		"NETWORK_POLICY":  2,
		"WORKSPACE":       100,
		"SHARE":           101,
		"SCHEMA":          200,
		"DATALAKE":        201,
		"USER":            202,
		"ROLE":            203,
		"VIRTUAL_CLUSTER": 104,
		"JOB":             205,
		"CONNECTION":      206,
		"TABLE":           300,
		"FUNCTION":        301,
		"INDEX":           400,
		"FILE":            500,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_util_object_identifier_proto_enumTypes[0].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_util_object_identifier_proto_enumTypes[0]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_util_object_identifier_proto_rawDescGZIP(), []int{0}
}

type PrincipalType int32

const (
	PrincipalType_PT_USER             PrincipalType = 0
	PrincipalType_PT_SYSTEM           PrincipalType = 1
	PrincipalType_PT_SERVICE_SYSTEM   PrincipalType = 2
	PrincipalType_PT_SERVICE_CUSTOMER PrincipalType = 4
)

// Enum value maps for PrincipalType.
var (
	PrincipalType_name = map[int32]string{
		0: "PT_USER",
		1: "PT_SYSTEM",
		2: "PT_SERVICE_SYSTEM",
		4: "PT_SERVICE_CUSTOMER",
	}
	PrincipalType_value = map[string]int32{
		"PT_USER":             0,
		"PT_SYSTEM":           1,
		"PT_SERVICE_SYSTEM":   2,
		"PT_SERVICE_CUSTOMER": 4,
	}
)

func (x PrincipalType) Enum() *PrincipalType {
	p := new(PrincipalType)
	*p = x
	return p
}

func (x PrincipalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrincipalType) Descriptor() protoreflect.EnumDescriptor {
	return file_util_object_identifier_proto_enumTypes[1].Descriptor()
}

func (PrincipalType) Type() protoreflect.EnumType {
	return &file_util_object_identifier_proto_enumTypes[1]
}

func (x PrincipalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrincipalType.Descriptor instead.
func (PrincipalType) EnumDescriptor() ([]byte, []int) {
	return file_util_object_identifier_proto_rawDescGZIP(), []int{1}
}

type ObjectState_Type int32

const (
	ObjectState_ONLINE  ObjectState_Type = 0
	ObjectState_DELETED ObjectState_Type = 1
	ObjectState_STAGED  ObjectState_Type = 2
)

// Enum value maps for ObjectState_Type.
var (
	ObjectState_Type_name = map[int32]string{
		0: "ONLINE",
		1: "DELETED",
		2: "STAGED",
	}
	ObjectState_Type_value = map[string]int32{
		"ONLINE":  0,
		"DELETED": 1,
		"STAGED":  2,
	}
)

func (x ObjectState_Type) Enum() *ObjectState_Type {
	p := new(ObjectState_Type)
	*p = x
	return p
}

func (x ObjectState_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectState_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_util_object_identifier_proto_enumTypes[2].Descriptor()
}

func (ObjectState_Type) Type() protoreflect.EnumType {
	return &file_util_object_identifier_proto_enumTypes[2]
}

func (x ObjectState_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectState_Type.Descriptor instead.
func (ObjectState_Type) EnumDescriptor() ([]byte, []int) {
	return file_util_object_identifier_proto_rawDescGZIP(), []int{0, 0}
}

type ObjectState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ObjectState) Reset() {
	*x = ObjectState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_object_identifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectState) ProtoMessage() {}

func (x *ObjectState) ProtoReflect() protoreflect.Message {
	mi := &file_util_object_identifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectState.ProtoReflect.Descriptor instead.
func (*ObjectState) Descriptor() ([]byte, []int) {
	return file_util_object_identifier_proto_rawDescGZIP(), []int{0}
}

type ObjectIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ObjectType `protobuf:"varint,1,opt,name=type,proto3,enum=util.ObjectType" json:"type,omitempty"`
	// account identifier
	AccountId   *int64  `protobuf:"varint,6,opt,name=account_id,json=accountId,proto3,oneof" json:"account_id,omitempty"`
	AccountName *string `protobuf:"bytes,7,opt,name=account_name,json=accountName,proto3,oneof" json:"account_name,omitempty"`
	// instance identifier
	InstanceId   int64   `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	InstanceName *string `protobuf:"bytes,5,opt,name=instance_name,json=instanceName,proto3,oneof" json:"instance_name,omitempty"`
	// namespace identifier
	Namespace   []string `protobuf:"bytes,3,rep,name=namespace,proto3" json:"namespace,omitempty"`
	NamespaceId []int64  `protobuf:"varint,10,rep,packed,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	// object identifier
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ObjectIdentifier) Reset() {
	*x = ObjectIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_object_identifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectIdentifier) ProtoMessage() {}

func (x *ObjectIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_util_object_identifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectIdentifier.ProtoReflect.Descriptor instead.
func (*ObjectIdentifier) Descriptor() ([]byte, []int) {
	return file_util_object_identifier_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectIdentifier) GetType() ObjectType {
	if x != nil {
		return x.Type
	}
	return ObjectType_UNKNOWN
}

func (x *ObjectIdentifier) GetAccountId() int64 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *ObjectIdentifier) GetAccountName() string {
	if x != nil && x.AccountName != nil {
		return *x.AccountName
	}
	return ""
}

func (x *ObjectIdentifier) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *ObjectIdentifier) GetInstanceName() string {
	if x != nil && x.InstanceName != nil {
		return *x.InstanceName
	}
	return ""
}

func (x *ObjectIdentifier) GetNamespace() []string {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *ObjectIdentifier) GetNamespaceId() []int64 {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *ObjectIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectIdentifier) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ObjectIdentifierList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifiers []*ObjectIdentifier `protobuf:"bytes,1,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
}

func (x *ObjectIdentifierList) Reset() {
	*x = ObjectIdentifierList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_object_identifier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectIdentifierList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectIdentifierList) ProtoMessage() {}

func (x *ObjectIdentifierList) ProtoReflect() protoreflect.Message {
	mi := &file_util_object_identifier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectIdentifierList.ProtoReflect.Descriptor instead.
func (*ObjectIdentifierList) Descriptor() ([]byte, []int) {
	return file_util_object_identifier_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectIdentifierList) GetIdentifiers() []*ObjectIdentifier {
	if x != nil {
		return x.Identifiers
	}
	return nil
}

var File_util_object_identifier_proto protoreflect.FileDescriptor

var file_util_object_identifier_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x75, 0x74, 0x69, 0x6c, 0x22, 0x3a, 0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x2b, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4f,
	0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x41, 0x47, 0x45, 0x44, 0x10, 0x02,
	0x22, 0xe6, 0x02, 0x0a, 0x10, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0a, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x48,
	0x00, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12,
	0x26, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x02, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x14, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x38, 0x0a, 0x0b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0b,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x2a, 0xe9, 0x01, 0x0a, 0x0a,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x53, 0x54, 0x41,
	0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b,
	0x5f, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x4f, 0x52,
	0x4b, 0x53, 0x50, 0x41, 0x43, 0x45, 0x10, 0x64, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x48, 0x41, 0x52,
	0x45, 0x10, 0x65, 0x12, 0x0b, 0x0a, 0x06, 0x53, 0x43, 0x48, 0x45, 0x4d, 0x41, 0x10, 0xc8, 0x01,
	0x12, 0x0d, 0x0a, 0x08, 0x44, 0x41, 0x54, 0x41, 0x4c, 0x41, 0x4b, 0x45, 0x10, 0xc9, 0x01, 0x12,
	0x09, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0xca, 0x01, 0x12, 0x09, 0x0a, 0x04, 0x52, 0x4f,
	0x4c, 0x45, 0x10, 0xcb, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x56, 0x49, 0x52, 0x54, 0x55, 0x41, 0x4c,
	0x5f, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x10, 0x68, 0x12, 0x08, 0x0a, 0x03, 0x4a, 0x4f,
	0x42, 0x10, 0xcd, 0x01, 0x12, 0x0f, 0x0a, 0x0a, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x10, 0xce, 0x01, 0x12, 0x0a, 0x0a, 0x05, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0xac,
	0x02, 0x12, 0x0d, 0x0a, 0x08, 0x46, 0x55, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0xad, 0x02,
	0x12, 0x0a, 0x0a, 0x05, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x10, 0x90, 0x03, 0x12, 0x09, 0x0a, 0x04,
	0x46, 0x49, 0x4c, 0x45, 0x10, 0xf4, 0x03, 0x2a, 0x5b, 0x0a, 0x0d, 0x50, 0x72, 0x69, 0x6e, 0x63,
	0x69, 0x70, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x54, 0x5f, 0x55,
	0x53, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x54, 0x5f, 0x53, 0x59, 0x53, 0x54,
	0x45, 0x4d, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x54, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49,
	0x43, 0x45, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x50,
	0x54, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d,
	0x45, 0x52, 0x10, 0x04, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f, 0x67, 0x6f,
	0x63, 0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x62, 0x75, 0x6c, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_util_object_identifier_proto_rawDescOnce sync.Once
	file_util_object_identifier_proto_rawDescData = file_util_object_identifier_proto_rawDesc
)

func file_util_object_identifier_proto_rawDescGZIP() []byte {
	file_util_object_identifier_proto_rawDescOnce.Do(func() {
		file_util_object_identifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_util_object_identifier_proto_rawDescData)
	})
	return file_util_object_identifier_proto_rawDescData
}

var file_util_object_identifier_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_util_object_identifier_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_util_object_identifier_proto_goTypes = []interface{}{
	(ObjectType)(0),              // 0: util.ObjectType
	(PrincipalType)(0),           // 1: util.PrincipalType
	(ObjectState_Type)(0),        // 2: util.ObjectState.Type
	(*ObjectState)(nil),          // 3: util.ObjectState
	(*ObjectIdentifier)(nil),     // 4: util.ObjectIdentifier
	(*ObjectIdentifierList)(nil), // 5: util.ObjectIdentifierList
}
var file_util_object_identifier_proto_depIdxs = []int32{
	0, // 0: util.ObjectIdentifier.type:type_name -> util.ObjectType
	4, // 1: util.ObjectIdentifierList.identifiers:type_name -> util.ObjectIdentifier
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_util_object_identifier_proto_init() }
func file_util_object_identifier_proto_init() {
	if File_util_object_identifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_util_object_identifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_util_object_identifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_util_object_identifier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectIdentifierList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_util_object_identifier_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_util_object_identifier_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_object_identifier_proto_goTypes,
		DependencyIndexes: file_util_object_identifier_proto_depIdxs,
		EnumInfos:         file_util_object_identifier_proto_enumTypes,
		MessageInfos:      file_util_object_identifier_proto_msgTypes,
	}.Build()
	File_util_object_identifier_proto = out.File
	file_util_object_identifier_proto_rawDesc = nil
	file_util_object_identifier_proto_goTypes = nil
	file_util_object_identifier_proto_depIdxs = nil
}
