// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: util/role_meta.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleType int32

const (
	RoleType_RT_SYSTEM    RoleType = 0
	RoleType_RT_CUSTOMIZE RoleType = 1
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "RT_SYSTEM",
		1: "RT_CUSTOMIZE",
	}
	RoleType_value = map[string]int32{
		"RT_SYSTEM":    0,
		"RT_CUSTOMIZE": 1,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_util_role_meta_proto_enumTypes[0].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_util_role_meta_proto_enumTypes[0]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_util_role_meta_proto_rawDescGZIP(), []int{0}
}

type RoleLevel int32

const (
	RoleLevel_RL_SYSTEM    RoleLevel = 0
	RoleLevel_RL_WORKSPACE RoleLevel = 1
)

// Enum value maps for RoleLevel.
var (
	RoleLevel_name = map[int32]string{
		0: "RL_SYSTEM",
		1: "RL_WORKSPACE",
	}
	RoleLevel_value = map[string]int32{
		"RL_SYSTEM":    0,
		"RL_WORKSPACE": 1,
	}
)

func (x RoleLevel) Enum() *RoleLevel {
	p := new(RoleLevel)
	*p = x
	return p
}

func (x RoleLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_util_role_meta_proto_enumTypes[1].Descriptor()
}

func (RoleLevel) Type() protoreflect.EnumType {
	return &file_util_role_meta_proto_enumTypes[1]
}

func (x RoleLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleLevel.Descriptor instead.
func (RoleLevel) EnumDescriptor() ([]byte, []int) {
	return file_util_role_meta_proto_rawDescGZIP(), []int{1}
}

type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alias string    `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Type  RoleType  `protobuf:"varint,2,opt,name=type,proto3,enum=util.RoleType" json:"type,omitempty"`
	Level RoleLevel `protobuf:"varint,3,opt,name=level,proto3,enum=util.RoleLevel" json:"level,omitempty"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_role_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_util_role_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_util_role_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Role) GetType() RoleType {
	if x != nil {
		return x.Type
	}
	return RoleType_RT_SYSTEM
}

func (x *Role) GetLevel() RoleLevel {
	if x != nil {
		return x.Level
	}
	return RoleLevel_RL_SYSTEM
}

var File_util_role_meta_proto protoreflect.FileDescriptor

var file_util_role_meta_proto_rawDesc = []byte{
	0x0a, 0x14, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x74, 0x69, 0x6c, 0x22, 0x67, 0x0a, 0x04,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e,
	0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25,
	0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x75, 0x74, 0x69, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2a, 0x2b, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x54, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x52, 0x54, 0x5f, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x49, 0x5a, 0x45,
	0x10, 0x01, 0x2a, 0x2c, 0x0a, 0x09, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x0d, 0x0a, 0x09, 0x52, 0x4c, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x52, 0x4c, 0x5f, 0x57, 0x4f, 0x52, 0x4b, 0x53, 0x50, 0x41, 0x43, 0x45, 0x10, 0x01,
	0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x63,
	0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x75,
	0x6c, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_util_role_meta_proto_rawDescOnce sync.Once
	file_util_role_meta_proto_rawDescData = file_util_role_meta_proto_rawDesc
)

func file_util_role_meta_proto_rawDescGZIP() []byte {
	file_util_role_meta_proto_rawDescOnce.Do(func() {
		file_util_role_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_util_role_meta_proto_rawDescData)
	})
	return file_util_role_meta_proto_rawDescData
}

var file_util_role_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_util_role_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_util_role_meta_proto_goTypes = []interface{}{
	(RoleType)(0),  // 0: util.RoleType
	(RoleLevel)(0), // 1: util.RoleLevel
	(*Role)(nil),   // 2: util.Role
}
var file_util_role_meta_proto_depIdxs = []int32{
	0, // 0: util.Role.type:type_name -> util.RoleType
	1, // 1: util.Role.level:type_name -> util.RoleLevel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_util_role_meta_proto_init() }
func file_util_role_meta_proto_init() {
	if File_util_role_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_util_role_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_util_role_meta_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_role_meta_proto_goTypes,
		DependencyIndexes: file_util_role_meta_proto_depIdxs,
		EnumInfos:         file_util_role_meta_proto_enumTypes,
		MessageInfos:      file_util_role_meta_proto_msgTypes,
	}.Build()
	File_util_role_meta_proto = out.File
	file_util_role_meta_proto_rawDesc = nil
	file_util_role_meta_proto_goTypes = nil
	file_util_role_meta_proto_depIdxs = nil
}
