// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: util/share_meta.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Share_Kind int32

const (
	Share_INBOUND  Share_Kind = 0
	Share_OUTBOUND Share_Kind = 1
)

// Enum value maps for Share_Kind.
var (
	Share_Kind_name = map[int32]string{
		0: "INBOUND",
		1: "OUTBOUND",
	}
	Share_Kind_value = map[string]int32{
		"INBOUND":  0,
		"OUTBOUND": 1,
	}
)

func (x Share_Kind) Enum() *Share_Kind {
	p := new(Share_Kind)
	*p = x
	return p
}

func (x Share_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Share_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_util_share_meta_proto_enumTypes[0].Descriptor()
}

func (Share_Kind) Type() protoreflect.EnumType {
	return &file_util_share_meta_proto_enumTypes[0]
}

func (x Share_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Share_Kind.Descriptor instead.
func (Share_Kind) EnumDescriptor() ([]byte, []int) {
	return file_util_share_meta_proto_rawDescGZIP(), []int{0, 0}
}

type Share_Scope int32

const (
	Share_PRIVATE Share_Scope = 0
	Share_PUBLIC  Share_Scope = 1
)

// Enum value maps for Share_Scope.
var (
	Share_Scope_name = map[int32]string{
		0: "PRIVATE",
		1: "PUBLIC",
	}
	Share_Scope_value = map[string]int32{
		"PRIVATE": 0,
		"PUBLIC":  1,
	}
)

func (x Share_Scope) Enum() *Share_Scope {
	p := new(Share_Scope)
	*p = x
	return p
}

func (x Share_Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Share_Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_util_share_meta_proto_enumTypes[1].Descriptor()
}

func (Share_Scope) Type() protoreflect.EnumType {
	return &file_util_share_meta_proto_enumTypes[1]
}

func (x Share_Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Share_Scope.Descriptor instead.
func (Share_Scope) EnumDescriptor() ([]byte, []int) {
	return file_util_share_meta_proto_rawDescGZIP(), []int{0, 1}
}

type Share struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderWorkspace *ObjectIdentifier `protobuf:"bytes,1,opt,name=provider_workspace,json=providerWorkspace,proto3" json:"provider_workspace,omitempty"`
	// Kind is only for show shares
	Kind  Share_Kind  `protobuf:"varint,2,opt,name=kind,proto3,enum=util.Share_Kind" json:"kind,omitempty"`
	Scope Share_Scope `protobuf:"varint,3,opt,name=scope,proto3,enum=util.Share_Scope" json:"scope,omitempty"`
}

func (x *Share) Reset() {
	*x = Share{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_share_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Share) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share) ProtoMessage() {}

func (x *Share) ProtoReflect() protoreflect.Message {
	mi := &file_util_share_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share.ProtoReflect.Descriptor instead.
func (*Share) Descriptor() ([]byte, []int) {
	return file_util_share_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Share) GetProviderWorkspace() *ObjectIdentifier {
	if x != nil {
		return x.ProviderWorkspace
	}
	return nil
}

func (x *Share) GetKind() Share_Kind {
	if x != nil {
		return x.Kind
	}
	return Share_INBOUND
}

func (x *Share) GetScope() Share_Scope {
	if x != nil {
		return x.Scope
	}
	return Share_PRIVATE
}

var File_util_share_meta_proto protoreflect.FileDescriptor

var file_util_share_meta_proto_rawDesc = []byte{
	0x0a, 0x15, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x74, 0x69, 0x6c, 0x1a, 0x1c, 0x75,
	0x74, 0x69, 0x6c, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe2, 0x01, 0x0a, 0x05,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x45, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x11, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x75, 0x74, 0x69,
	0x6c, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x53,
	0x63, 0x6f, 0x70, 0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x22, 0x21, 0x0a, 0x04, 0x4b,
	0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x42, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x55, 0x54, 0x42, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x22, 0x20,
	0x0a, 0x05, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x49, 0x56, 0x41,
	0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x10, 0x01,
	0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x63,
	0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x75,
	0x6c, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_util_share_meta_proto_rawDescOnce sync.Once
	file_util_share_meta_proto_rawDescData = file_util_share_meta_proto_rawDesc
)

func file_util_share_meta_proto_rawDescGZIP() []byte {
	file_util_share_meta_proto_rawDescOnce.Do(func() {
		file_util_share_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_util_share_meta_proto_rawDescData)
	})
	return file_util_share_meta_proto_rawDescData
}

var file_util_share_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_util_share_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_util_share_meta_proto_goTypes = []interface{}{
	(Share_Kind)(0),          // 0: util.Share.Kind
	(Share_Scope)(0),         // 1: util.Share.Scope
	(*Share)(nil),            // 2: util.Share
	(*ObjectIdentifier)(nil), // 3: util.ObjectIdentifier
}
var file_util_share_meta_proto_depIdxs = []int32{
	3, // 0: util.Share.provider_workspace:type_name -> util.ObjectIdentifier
	0, // 1: util.Share.kind:type_name -> util.Share.Kind
	1, // 2: util.Share.scope:type_name -> util.Share.Scope
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_util_share_meta_proto_init() }
func file_util_share_meta_proto_init() {
	if File_util_share_meta_proto != nil {
		return
	}
	file_util_object_identifier_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_util_share_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Share); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_util_share_meta_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_share_meta_proto_goTypes,
		DependencyIndexes: file_util_share_meta_proto_depIdxs,
		EnumInfos:         file_util_share_meta_proto_enumTypes,
		MessageInfos:      file_util_share_meta_proto_msgTypes,
	}.Build()
	File_util_share_meta_proto = out.File
	file_util_share_meta_proto_rawDesc = nil
	file_util_share_meta_proto_goTypes = nil
	file_util_share_meta_proto_depIdxs = nil
}
