// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: util/virtual_value_info.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConstantField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId   uint32    `protobuf:"varint,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Type      *DataType `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value     *Constant `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	FieldName *string   `protobuf:"bytes,10,opt,name=field_name,json=fieldName,proto3,oneof" json:"field_name,omitempty"` // only used in commit log
}

func (x *ConstantField) Reset() {
	*x = ConstantField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_virtual_value_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConstantField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstantField) ProtoMessage() {}

func (x *ConstantField) ProtoReflect() protoreflect.Message {
	mi := &file_util_virtual_value_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstantField.ProtoReflect.Descriptor instead.
func (*ConstantField) Descriptor() ([]byte, []int) {
	return file_util_virtual_value_info_proto_rawDescGZIP(), []int{0}
}

func (x *ConstantField) GetFieldId() uint32 {
	if x != nil {
		return x.FieldId
	}
	return 0
}

func (x *ConstantField) GetType() *DataType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ConstantField) GetValue() *Constant {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConstantField) GetFieldName() string {
	if x != nil && x.FieldName != nil {
		return *x.FieldName
	}
	return ""
}

// hive support some virtual columns:
//
//	INPUT__FILE__NAME, which is the input file's name for a mapper task.
//	BLOCK__OFFSET__INSIDE__FILE, which is the current global file position.
//	ROW__OFFSET__INSIDE__BLOCK
//	RAW__DATA__SIZE
//	ROW__ID
//	GROUPING__ID
//
// different systems have different semantics,
// It like:
//
//	presto not support virtual columns
//	mysql and oracle support virtual columns, it called generated columns
//	sql server called computed columns, marked PERSISTED, it will be stored in the table
type VirtualColumnValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*ConstantField `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	// maybe only contains partial blocks
	BlockIds []uint32 `protobuf:"varint,2,rep,packed,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
}

func (x *VirtualColumnValues) Reset() {
	*x = VirtualColumnValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_virtual_value_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualColumnValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualColumnValues) ProtoMessage() {}

func (x *VirtualColumnValues) ProtoReflect() protoreflect.Message {
	mi := &file_util_virtual_value_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualColumnValues.ProtoReflect.Descriptor instead.
func (*VirtualColumnValues) Descriptor() ([]byte, []int) {
	return file_util_virtual_value_info_proto_rawDescGZIP(), []int{1}
}

func (x *VirtualColumnValues) GetValues() []*ConstantField {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *VirtualColumnValues) GetBlockIds() []uint32 {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

type VirtualValueInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VirtualValues *VirtualColumnValues `protobuf:"bytes,1,opt,name=virtual_values,json=virtualValues,proto3" json:"virtual_values,omitempty"`
}

func (x *VirtualValueInfo) Reset() {
	*x = VirtualValueInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_virtual_value_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualValueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualValueInfo) ProtoMessage() {}

func (x *VirtualValueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_util_virtual_value_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualValueInfo.ProtoReflect.Descriptor instead.
func (*VirtualValueInfo) Descriptor() ([]byte, []int) {
	return file_util_virtual_value_info_proto_rawDescGZIP(), []int{2}
}

func (x *VirtualValueInfo) GetVirtualValues() *VirtualColumnValues {
	if x != nil {
		return x.VirtualValues
	}
	return nil
}

var File_util_virtual_value_info_proto protoreflect.FileDescriptor

var file_util_virtual_value_info_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x75, 0x74, 0x69, 0x6c, 0x1a, 0x15, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x65, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x75, 0x74,
	0x69, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x75, 0x74, 0x69, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0a, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a, 0x13,
	0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x73, 0x22, 0x54, 0x0a,
	0x10, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x40, 0x0a, 0x0e, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x75, 0x74, 0x69, 0x6c,
	0x2e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x52, 0x0d, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x63,
	0x6c, 0x69, 0x63, 0x6b, 0x7a, 0x65, 0x74, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x62, 0x75, 0x6c, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_util_virtual_value_info_proto_rawDescOnce sync.Once
	file_util_virtual_value_info_proto_rawDescData = file_util_virtual_value_info_proto_rawDesc
)

func file_util_virtual_value_info_proto_rawDescGZIP() []byte {
	file_util_virtual_value_info_proto_rawDescOnce.Do(func() {
		file_util_virtual_value_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_util_virtual_value_info_proto_rawDescData)
	})
	return file_util_virtual_value_info_proto_rawDescData
}

var file_util_virtual_value_info_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_util_virtual_value_info_proto_goTypes = []interface{}{
	(*ConstantField)(nil),       // 0: util.ConstantField
	(*VirtualColumnValues)(nil), // 1: util.VirtualColumnValues
	(*VirtualValueInfo)(nil),    // 2: util.VirtualValueInfo
	(*DataType)(nil),            // 3: util.DataType
	(*Constant)(nil),            // 4: util.Constant
}
var file_util_virtual_value_info_proto_depIdxs = []int32{
	3, // 0: util.ConstantField.type:type_name -> util.DataType
	4, // 1: util.ConstantField.value:type_name -> util.Constant
	0, // 2: util.VirtualColumnValues.values:type_name -> util.ConstantField
	1, // 3: util.VirtualValueInfo.virtual_values:type_name -> util.VirtualColumnValues
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_util_virtual_value_info_proto_init() }
func file_util_virtual_value_info_proto_init() {
	if File_util_virtual_value_info_proto != nil {
		return
	}
	file_util_expression_proto_init()
	file_util_data_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_util_virtual_value_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConstantField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_util_virtual_value_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualColumnValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_util_virtual_value_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualValueInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_util_virtual_value_info_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_util_virtual_value_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_virtual_value_info_proto_goTypes,
		DependencyIndexes: file_util_virtual_value_info_proto_depIdxs,
		MessageInfos:      file_util_virtual_value_info_proto_msgTypes,
	}.Build()
	File_util_virtual_value_info_proto = out.File
	file_util_virtual_value_info_proto_rawDesc = nil
	file_util_virtual_value_info_proto_goTypes = nil
	file_util_virtual_value_info_proto_depIdxs = nil
}
