// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: ingestion/ingestion.proto

package ingestion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestionControllerService_GatewayRpcCall_FullMethodName             = "/ingestion.IngestionControllerService/GatewayRpcCall"
	IngestionControllerService_CreateOrGetStream_FullMethodName          = "/ingestion.IngestionControllerService/CreateOrGetStream"
	IngestionControllerService_CloseStream_FullMethodName                = "/ingestion.IngestionControllerService/CloseStream"
	IngestionControllerService_GetRouteWorkers_FullMethodName            = "/ingestion.IngestionControllerService/GetRouteWorkers"
	IngestionControllerService_CreateBulkLoadStream_FullMethodName       = "/ingestion.IngestionControllerService/CreateBulkLoadStream"
	IngestionControllerService_GetBulkLoadStream_FullMethodName          = "/ingestion.IngestionControllerService/GetBulkLoadStream"
	IngestionControllerService_CommitBulkLoadStream_FullMethodName       = "/ingestion.IngestionControllerService/CommitBulkLoadStream"
	IngestionControllerService_OpenBulkLoadStreamWriter_FullMethodName   = "/ingestion.IngestionControllerService/OpenBulkLoadStreamWriter"
	IngestionControllerService_FinishBulkLoadStreamWriter_FullMethodName = "/ingestion.IngestionControllerService/FinishBulkLoadStreamWriter"
)

// IngestionControllerServiceClient is the client API for IngestionControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestionControllerServiceClient interface {
	GatewayRpcCall(ctx context.Context, in *GatewayRequest, opts ...grpc.CallOption) (*GatewayResponse, error)
	CreateOrGetStream(ctx context.Context, in *CreateOrGetStreamRequest, opts ...grpc.CallOption) (*CreateOrGetStreamResponse, error)
	CloseStream(ctx context.Context, in *CloseStreamRequest, opts ...grpc.CallOption) (*CloseStreamResponse, error)
	GetRouteWorkers(ctx context.Context, in *GetRouteWorkersRequest, opts ...grpc.CallOption) (*GetRouteWorkersResponse, error)
	CreateBulkLoadStream(ctx context.Context, in *CreateBulkLoadStreamRequest, opts ...grpc.CallOption) (*CreateBulkLoadStreamResponse, error)
	GetBulkLoadStream(ctx context.Context, in *GetBulkLoadStreamRequest, opts ...grpc.CallOption) (*GetBulkLoadStreamResponse, error)
	CommitBulkLoadStream(ctx context.Context, in *CommitBulkLoadStreamRequest, opts ...grpc.CallOption) (*CommitBulkLoadStreamResponse, error)
	OpenBulkLoadStreamWriter(ctx context.Context, in *OpenBulkLoadStreamWriterRequest, opts ...grpc.CallOption) (*OpenBulkLoadStreamWriterResponse, error)
	FinishBulkLoadStreamWriter(ctx context.Context, in *FinishBulkLoadStreamWriterRequest, opts ...grpc.CallOption) (*FinishBulkLoadStreamWriterResponse, error)
}

type ingestionControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionControllerServiceClient(cc grpc.ClientConnInterface) IngestionControllerServiceClient {
	return &ingestionControllerServiceClient{cc}
}

func (c *ingestionControllerServiceClient) GatewayRpcCall(ctx context.Context, in *GatewayRequest, opts ...grpc.CallOption) (*GatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayResponse)
	err := c.cc.Invoke(ctx, IngestionControllerService_GatewayRpcCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionControllerServiceClient) CreateOrGetStream(ctx context.Context, in *CreateOrGetStreamRequest, opts ...grpc.CallOption) (*CreateOrGetStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrGetStreamResponse)
	err := c.cc.Invoke(ctx, IngestionControllerService_CreateOrGetStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionControllerServiceClient) CloseStream(ctx context.Context, in *CloseStreamRequest, opts ...grpc.CallOption) (*CloseStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseStreamResponse)
	err := c.cc.Invoke(ctx, IngestionControllerService_CloseStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionControllerServiceClient) GetRouteWorkers(ctx context.Context, in *GetRouteWorkersRequest, opts ...grpc.CallOption) (*GetRouteWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteWorkersResponse)
	err := c.cc.Invoke(ctx, IngestionControllerService_GetRouteWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionControllerServiceClient) CreateBulkLoadStream(ctx context.Context, in *CreateBulkLoadStreamRequest, opts ...grpc.CallOption) (*CreateBulkLoadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBulkLoadStreamResponse)
	err := c.cc.Invoke(ctx, IngestionControllerService_CreateBulkLoadStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionControllerServiceClient) GetBulkLoadStream(ctx context.Context, in *GetBulkLoadStreamRequest, opts ...grpc.CallOption) (*GetBulkLoadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBulkLoadStreamResponse)
	err := c.cc.Invoke(ctx, IngestionControllerService_GetBulkLoadStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionControllerServiceClient) CommitBulkLoadStream(ctx context.Context, in *CommitBulkLoadStreamRequest, opts ...grpc.CallOption) (*CommitBulkLoadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitBulkLoadStreamResponse)
	err := c.cc.Invoke(ctx, IngestionControllerService_CommitBulkLoadStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionControllerServiceClient) OpenBulkLoadStreamWriter(ctx context.Context, in *OpenBulkLoadStreamWriterRequest, opts ...grpc.CallOption) (*OpenBulkLoadStreamWriterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenBulkLoadStreamWriterResponse)
	err := c.cc.Invoke(ctx, IngestionControllerService_OpenBulkLoadStreamWriter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionControllerServiceClient) FinishBulkLoadStreamWriter(ctx context.Context, in *FinishBulkLoadStreamWriterRequest, opts ...grpc.CallOption) (*FinishBulkLoadStreamWriterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishBulkLoadStreamWriterResponse)
	err := c.cc.Invoke(ctx, IngestionControllerService_FinishBulkLoadStreamWriter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngestionControllerServiceServer is the server API for IngestionControllerService service.
// All implementations must embed UnimplementedIngestionControllerServiceServer
// for forward compatibility.
type IngestionControllerServiceServer interface {
	GatewayRpcCall(context.Context, *GatewayRequest) (*GatewayResponse, error)
	CreateOrGetStream(context.Context, *CreateOrGetStreamRequest) (*CreateOrGetStreamResponse, error)
	CloseStream(context.Context, *CloseStreamRequest) (*CloseStreamResponse, error)
	GetRouteWorkers(context.Context, *GetRouteWorkersRequest) (*GetRouteWorkersResponse, error)
	CreateBulkLoadStream(context.Context, *CreateBulkLoadStreamRequest) (*CreateBulkLoadStreamResponse, error)
	GetBulkLoadStream(context.Context, *GetBulkLoadStreamRequest) (*GetBulkLoadStreamResponse, error)
	CommitBulkLoadStream(context.Context, *CommitBulkLoadStreamRequest) (*CommitBulkLoadStreamResponse, error)
	OpenBulkLoadStreamWriter(context.Context, *OpenBulkLoadStreamWriterRequest) (*OpenBulkLoadStreamWriterResponse, error)
	FinishBulkLoadStreamWriter(context.Context, *FinishBulkLoadStreamWriterRequest) (*FinishBulkLoadStreamWriterResponse, error)
	mustEmbedUnimplementedIngestionControllerServiceServer()
}

// UnimplementedIngestionControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestionControllerServiceServer struct{}

func (UnimplementedIngestionControllerServiceServer) GatewayRpcCall(context.Context, *GatewayRequest) (*GatewayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GatewayRpcCall not implemented")
}
func (UnimplementedIngestionControllerServiceServer) CreateOrGetStream(context.Context, *CreateOrGetStreamRequest) (*CreateOrGetStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrGetStream not implemented")
}
func (UnimplementedIngestionControllerServiceServer) CloseStream(context.Context, *CloseStreamRequest) (*CloseStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseStream not implemented")
}
func (UnimplementedIngestionControllerServiceServer) GetRouteWorkers(context.Context, *GetRouteWorkersRequest) (*GetRouteWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRouteWorkers not implemented")
}
func (UnimplementedIngestionControllerServiceServer) CreateBulkLoadStream(context.Context, *CreateBulkLoadStreamRequest) (*CreateBulkLoadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBulkLoadStream not implemented")
}
func (UnimplementedIngestionControllerServiceServer) GetBulkLoadStream(context.Context, *GetBulkLoadStreamRequest) (*GetBulkLoadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBulkLoadStream not implemented")
}
func (UnimplementedIngestionControllerServiceServer) CommitBulkLoadStream(context.Context, *CommitBulkLoadStreamRequest) (*CommitBulkLoadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitBulkLoadStream not implemented")
}
func (UnimplementedIngestionControllerServiceServer) OpenBulkLoadStreamWriter(context.Context, *OpenBulkLoadStreamWriterRequest) (*OpenBulkLoadStreamWriterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenBulkLoadStreamWriter not implemented")
}
func (UnimplementedIngestionControllerServiceServer) FinishBulkLoadStreamWriter(context.Context, *FinishBulkLoadStreamWriterRequest) (*FinishBulkLoadStreamWriterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishBulkLoadStreamWriter not implemented")
}
func (UnimplementedIngestionControllerServiceServer) mustEmbedUnimplementedIngestionControllerServiceServer() {
}
func (UnimplementedIngestionControllerServiceServer) testEmbeddedByValue() {}

// UnsafeIngestionControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionControllerServiceServer will
// result in compilation errors.
type UnsafeIngestionControllerServiceServer interface {
	mustEmbedUnimplementedIngestionControllerServiceServer()
}

func RegisterIngestionControllerServiceServer(s grpc.ServiceRegistrar, srv IngestionControllerServiceServer) {
	// If the following call panics, it indicates UnimplementedIngestionControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestionControllerService_ServiceDesc, srv)
}

func _IngestionControllerService_GatewayRpcCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionControllerServiceServer).GatewayRpcCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionControllerService_GatewayRpcCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionControllerServiceServer).GatewayRpcCall(ctx, req.(*GatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionControllerService_CreateOrGetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrGetStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionControllerServiceServer).CreateOrGetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionControllerService_CreateOrGetStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionControllerServiceServer).CreateOrGetStream(ctx, req.(*CreateOrGetStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionControllerService_CloseStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionControllerServiceServer).CloseStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionControllerService_CloseStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionControllerServiceServer).CloseStream(ctx, req.(*CloseStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionControllerService_GetRouteWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionControllerServiceServer).GetRouteWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionControllerService_GetRouteWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionControllerServiceServer).GetRouteWorkers(ctx, req.(*GetRouteWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionControllerService_CreateBulkLoadStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBulkLoadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionControllerServiceServer).CreateBulkLoadStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionControllerService_CreateBulkLoadStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionControllerServiceServer).CreateBulkLoadStream(ctx, req.(*CreateBulkLoadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionControllerService_GetBulkLoadStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBulkLoadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionControllerServiceServer).GetBulkLoadStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionControllerService_GetBulkLoadStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionControllerServiceServer).GetBulkLoadStream(ctx, req.(*GetBulkLoadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionControllerService_CommitBulkLoadStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitBulkLoadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionControllerServiceServer).CommitBulkLoadStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionControllerService_CommitBulkLoadStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionControllerServiceServer).CommitBulkLoadStream(ctx, req.(*CommitBulkLoadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionControllerService_OpenBulkLoadStreamWriter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenBulkLoadStreamWriterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionControllerServiceServer).OpenBulkLoadStreamWriter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionControllerService_OpenBulkLoadStreamWriter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionControllerServiceServer).OpenBulkLoadStreamWriter(ctx, req.(*OpenBulkLoadStreamWriterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionControllerService_FinishBulkLoadStreamWriter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishBulkLoadStreamWriterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionControllerServiceServer).FinishBulkLoadStreamWriter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionControllerService_FinishBulkLoadStreamWriter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionControllerServiceServer).FinishBulkLoadStreamWriter(ctx, req.(*FinishBulkLoadStreamWriterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IngestionControllerService_ServiceDesc is the grpc.ServiceDesc for IngestionControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestionControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingestion.IngestionControllerService",
	HandlerType: (*IngestionControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GatewayRpcCall",
			Handler:    _IngestionControllerService_GatewayRpcCall_Handler,
		},
		{
			MethodName: "CreateOrGetStream",
			Handler:    _IngestionControllerService_CreateOrGetStream_Handler,
		},
		{
			MethodName: "CloseStream",
			Handler:    _IngestionControllerService_CloseStream_Handler,
		},
		{
			MethodName: "GetRouteWorkers",
			Handler:    _IngestionControllerService_GetRouteWorkers_Handler,
		},
		{
			MethodName: "CreateBulkLoadStream",
			Handler:    _IngestionControllerService_CreateBulkLoadStream_Handler,
		},
		{
			MethodName: "GetBulkLoadStream",
			Handler:    _IngestionControllerService_GetBulkLoadStream_Handler,
		},
		{
			MethodName: "CommitBulkLoadStream",
			Handler:    _IngestionControllerService_CommitBulkLoadStream_Handler,
		},
		{
			MethodName: "OpenBulkLoadStreamWriter",
			Handler:    _IngestionControllerService_OpenBulkLoadStreamWriter_Handler,
		},
		{
			MethodName: "FinishBulkLoadStreamWriter",
			Handler:    _IngestionControllerService_FinishBulkLoadStreamWriter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingestion/ingestion.proto",
}

const (
	IngestionWorkerService_Mutate_FullMethodName         = "/ingestion.IngestionWorkerService/Mutate"
	IngestionWorkerService_MutateInternal_FullMethodName = "/ingestion.IngestionWorkerService/MutateInternal"
)

// IngestionWorkerServiceClient is the client API for IngestionWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestionWorkerServiceClient interface {
	Mutate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MutateRequest, MutateResponse], error)
	MutateInternal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MutateRequest, MutateResponse], error)
}

type ingestionWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionWorkerServiceClient(cc grpc.ClientConnInterface) IngestionWorkerServiceClient {
	return &ingestionWorkerServiceClient{cc}
}

func (c *ingestionWorkerServiceClient) Mutate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MutateRequest, MutateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestionWorkerService_ServiceDesc.Streams[0], IngestionWorkerService_Mutate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MutateRequest, MutateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionWorkerService_MutateClient = grpc.BidiStreamingClient[MutateRequest, MutateResponse]

func (c *ingestionWorkerServiceClient) MutateInternal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MutateRequest, MutateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestionWorkerService_ServiceDesc.Streams[1], IngestionWorkerService_MutateInternal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MutateRequest, MutateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionWorkerService_MutateInternalClient = grpc.BidiStreamingClient[MutateRequest, MutateResponse]

// IngestionWorkerServiceServer is the server API for IngestionWorkerService service.
// All implementations must embed UnimplementedIngestionWorkerServiceServer
// for forward compatibility.
type IngestionWorkerServiceServer interface {
	Mutate(grpc.BidiStreamingServer[MutateRequest, MutateResponse]) error
	MutateInternal(grpc.BidiStreamingServer[MutateRequest, MutateResponse]) error
	mustEmbedUnimplementedIngestionWorkerServiceServer()
}

// UnimplementedIngestionWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestionWorkerServiceServer struct{}

func (UnimplementedIngestionWorkerServiceServer) Mutate(grpc.BidiStreamingServer[MutateRequest, MutateResponse]) error {
	return status.Error(codes.Unimplemented, "method Mutate not implemented")
}
func (UnimplementedIngestionWorkerServiceServer) MutateInternal(grpc.BidiStreamingServer[MutateRequest, MutateResponse]) error {
	return status.Error(codes.Unimplemented, "method MutateInternal not implemented")
}
func (UnimplementedIngestionWorkerServiceServer) mustEmbedUnimplementedIngestionWorkerServiceServer() {
}
func (UnimplementedIngestionWorkerServiceServer) testEmbeddedByValue() {}

// UnsafeIngestionWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionWorkerServiceServer will
// result in compilation errors.
type UnsafeIngestionWorkerServiceServer interface {
	mustEmbedUnimplementedIngestionWorkerServiceServer()
}

func RegisterIngestionWorkerServiceServer(s grpc.ServiceRegistrar, srv IngestionWorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedIngestionWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestionWorkerService_ServiceDesc, srv)
}

func _IngestionWorkerService_Mutate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestionWorkerServiceServer).Mutate(&grpc.GenericServerStream[MutateRequest, MutateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionWorkerService_MutateServer = grpc.BidiStreamingServer[MutateRequest, MutateResponse]

func _IngestionWorkerService_MutateInternal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestionWorkerServiceServer).MutateInternal(&grpc.GenericServerStream[MutateRequest, MutateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionWorkerService_MutateInternalServer = grpc.BidiStreamingServer[MutateRequest, MutateResponse]

// IngestionWorkerService_ServiceDesc is the grpc.ServiceDesc for IngestionWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestionWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingestion.IngestionWorkerService",
	HandlerType: (*IngestionWorkerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Mutate",
			Handler:       _IngestionWorkerService_Mutate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "MutateInternal",
			Handler:       _IngestionWorkerService_MutateInternal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ingestion/ingestion.proto",
}
